name: 'Terraform Drift Detection'

on:
  # Run daily at 08:00 AM UTC (adjust schedule as needed)
  # schedule:
#   - cron: '*/6 * * * *'
  # Allow manual trigger from the GitHub UI
  workflow_dispatch:

jobs:
  drift_detection:
    name: 'Terraform Drift Check'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./terraform
    steps:
      - name: checkout code 
        uses: actions/checkout@v4

      - name: set up terraform
        uses: hashicorp/setup-terraform@v1 
        with:
          terraform_version: "1.15.9"
          terraform_wrapper: false

      - name: Configure AWS credential 
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION  }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan - Drift Check
        id: drift_check
        shell: bash
        run: |
          set +e
      
          terraform plan -detailed-exitcode
      
          EXIT_CODE=$?
      
          echo "exit_code=$EXIT_CODE" >> "$GITHUB_OUTPUT"
      
          if [ "$EXIT_CODE" -eq 0 ]; then
            echo "No drift detected."
            exit 0
          elif [ "$EXIT_CODE" -eq 2 ]; then
            echo "Drift detected!"
            exit 0
          else
            echo "Terraform plan failed."
            exit 1
          fi
